print("Name: Aryan Shahi")
print("Address: Shantinagar, Kathmandu")
print("Hobby: Learning new things.")
print("Recent Academic Achievement: +2 Completion")
print("Skills: Communication, Organizational")
print("Aim: Software/ Game Developer")
print("Languages: Nepali, English, Nepal Bhasa")
print("Programming Languages: C, QBASIC, JavaScript, Lua")
print("Achievements: WWF Quiz Second Runner Up, Soliditas De Mathematica Participation")
print("Motto: Never stop thriving towards your goal.")